"""Alert management and staff notification routes."""
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.auth.human import AuthenticatedUser, get_current_user, verify_store_access
from app.clients.data_service import data_client

router = APIRouter(prefix="/alerts", tags=["Alerts"])


class AcknowledgePayload(BaseModel):
    notes: Optional[str] = Field(None, json_schema_extra={"example": "Checked shelf; restock pallet on the way."})


@router.get("", status_code=status.HTTP_200_OK)
async def get_alerts(
    store_id: str = Query(..., alias="storeId"),
    status_filter: Optional[str] = Query(None, alias="status"),
    user: AuthenticatedUser = Depends(get_current_user),
) -> Dict[str, Any]:
    """List operational alerts generated by edge intelligence."""
    verify_store_access(user, store_id)
    alerts = await data_client.get_alerts(store_id=store_id, status=status_filter)
    return {"storeId": store_id, "count": len(alerts), "alerts": alerts}


@router.post("/{alert_id}/acknowledge", status_code=status.HTTP_200_OK)
async def acknowledge_alert(
    alert_id: str,
    payload: Optional[AcknowledgePayload] = None,
    user: AuthenticatedUser = Depends(get_current_user),
) -> Dict[str, Any]:
    """Acknowledge an active retail alert by a staff member or manager."""
    result = await data_client.acknowledge_alert(alert_id=alert_id, user_id=user.user_id)
    if not result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": {"code": "ALERT_NOT_FOUND", "message": f"Alert '{alert_id}' not found."}},
        )
    return result
